on: [push]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  # This workflow contains a single job called "build"

  build:

    # The type of runner that the job will run on

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v3

      # Runs a single command using the runners shell

      - name: SOOS DAST

      # You may pin to the exact commit or the version.

        uses: soos-io/soos-dast-github-action@v1.2.6

        with:

          client_id: ${{ secrets.SOOS_CLIENT_ID }}

          api_key: ${{ secrets.SOOS_API_KEY }}

          project_name: 'GH DAST QA'
          
          scan_mode: 'baseline'
          
          api_url: 'https://api.soos.io/api/'
          
          target_url: 'http://demo.testfire.net/'
          
      - name: SOOS SCA Scan

        uses: soos-io/soos-sca-github-action@v1.2.2

        with:

          project_name: 'SCA QA'

          client_id: ${{ secrets.SOOS_CLIENT_ID }}

          api_key: ${{ secrets.SOOS_API_KEY }}

          api_url: 'https://api.soos.io/api/'
